WEB_SERVER_HOST: 0.0.0.0
WEB_SERVER_PORT: 5000 

TEMP_DIR: '/workflux/tmp'
WORKFLOW_DIR: '/workflux/workflows'
EXEC_DIR: '/workflux/exec'
INPUT_DIR: '/workflux/input'
DB_DIR: '/workflux/database'

DEBUG: False


EXEC_PROFILES:
  toil:
    type: bash
    exec: |
      "toil-cwl-runner --outdir "${OUTPUT_DIR}" --log-file "${LOG_FILE}" "${WORKFLOW}" "${RUN_INPUT}"