apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
        - args:
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:8080
          image: traefik:v2.2
          name: traefik
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: traefik-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: traefik-hostpath0
status: {}
